#!/usr/bin/env python3
"""
MediaMeshMenu — ClickMesh-generated context menu extension for Caja (MATE).
Auto-generated by ClickMesh. Edit the source JSON and re-generate instead of
modifying this file directly.
"""

import os
import shlex
import subprocess
from urllib.parse import unquote

from gi.repository import Caja, GObject

# ---------------------------------------------------------------------------
#  Helpers
# ---------------------------------------------------------------------------

def _path_from_item(file_item):
    """Extract a local filesystem path from a Caja FileInfo object."""
    uri = file_item.get_uri()
    if uri.startswith("file://"):
        return unquote(uri[7:])
    return unquote(uri)

# ---------------------------------------------------------------------------
#  Action callbacks
# ---------------------------------------------------------------------------

def _on_action_0(menu_item, files):
    """Callback: Show Media Info"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -info %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Show Media Info': {exc}")


def _on_action_1(menu_item, files):
    """Callback: Convert to MP4"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -mp4 %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to MP4': {exc}")


def _on_action_2(menu_item, files):
    """Callback: Convert to MKV"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -mkv %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to MKV': {exc}")


def _on_action_3(menu_item, files):
    """Callback: Convert to WEBM"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -webm %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to WEBM': {exc}")


def _on_action_4(menu_item, files):
    """Callback: Convert to AV1"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -av1 %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to AV1': {exc}")


def _on_action_5(menu_item, files):
    """Callback: DaVinci Resolve (DNxHD)"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -davinci %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'DaVinci Resolve (DNxHD)': {exc}")


def _on_action_6(menu_item, files):
    """Callback: Apple ProRes (HQ)"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -prores %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Apple ProRes (HQ)': {exc}")


def _on_action_7(menu_item, files):
    """Callback: Extract Audio (MP3)"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -mp3 %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Extract Audio (MP3)': {exc}")


def _on_action_8(menu_item, files):
    """Callback: Extract Audio (AAC)"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -aac %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Extract Audio (AAC)': {exc}")


def _on_action_9(menu_item, files):
    """Callback: Extract Audio (WAV)"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -wav %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Extract Audio (WAV)': {exc}")


def _on_action_10(menu_item, files):
    """Callback: Convert to GIF"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -gif %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to GIF': {exc}")


def _on_action_11(menu_item, files):
    """Callback: Convert to WEBP"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -webp %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to WEBP': {exc}")


def _on_action_12(menu_item, files):
    """Callback: Convert to JPG"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -jpg %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to JPG': {exc}")


def _on_action_13(menu_item, files):
    """Callback: Convert to BMP"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -bmp %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to BMP': {exc}")


def _on_action_14(menu_item, files):
    """Callback: Convert to ICO"""
    for file_item in files:
        path = _path_from_item(file_item)
        cmd = 'media_mesh -ico %file'.replace("%file", shlex.quote(path))
        try:
            subprocess.Popen(
                cmd,
                shell=True,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[ClickMesh] Error in 'Convert to ICO': {exc}")


# ---------------------------------------------------------------------------
#  Menu Provider
# ---------------------------------------------------------------------------

class MediameshmenuExtension(GObject.GObject, Caja.MenuProvider):
    """Injects a 'Media Mesh Convert' submenu into the Caja right-click menu."""

    def get_file_items(self, window, files):
        if not files:
            return []

        # --- ClickMesh Filtering (Per-Item Basis Setup) ---
        allow_dirs = False
        paths = [_path_from_item(f) for f in files]
        has_dir = any(os.path.isdir(p) for p in paths)
        has_file = any(not os.path.isdir(p) for p in paths)

        if has_dir and not allow_dirs:
            return []
        # --------------------------------------------------

        top_item = Caja.MenuItem(
            name="MediaMeshMenu::TopMenu",
            label="Media Mesh Convert",
            tip="Media Mesh Convert",
            icon="video-x-generic",
        )
        submenu = Caja.Menu()
        top_item.set_submenu(submenu)

        items_added = 0
        item_0_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts', '.mp3', '.aac', '.wav', '.flac', '.ogg', '.m4a', '.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.ico')
        item_0_allow_all = False
        show_item_0 = False

        if has_dir and allow_dirs:
            show_item_0 = True
        elif has_file:
            if item_0_allow_all:
                show_item_0 = True
            else:
                show_item_0 = any(any(p.lower().endswith(ext) for ext in item_0_exts) for p in paths if not os.path.isdir(p))

        if show_item_0:
            item_0 = Caja.MenuItem(
                name="MediaMeshMenu::Action0",
                label="Show Media Info",
                tip="Show Media Info",
                icon="dialog-information",
            )
            item_0.connect("activate", _on_action_0, files)
            submenu.append_item(item_0)
            items_added += 1
        item_1_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts')
        item_1_allow_all = False
        show_item_1 = False

        if has_dir and allow_dirs:
            show_item_1 = True
        elif has_file:
            if item_1_allow_all:
                show_item_1 = True
            else:
                show_item_1 = any(any(p.lower().endswith(ext) for ext in item_1_exts) for p in paths if not os.path.isdir(p))

        if show_item_1:
            item_1 = Caja.MenuItem(
                name="MediaMeshMenu::Action1",
                label="Convert to MP4",
                tip="Convert to MP4",
                icon="video-x-generic",
            )
            item_1.connect("activate", _on_action_1, files)
            submenu.append_item(item_1)
            items_added += 1
        item_2_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts')
        item_2_allow_all = False
        show_item_2 = False

        if has_dir and allow_dirs:
            show_item_2 = True
        elif has_file:
            if item_2_allow_all:
                show_item_2 = True
            else:
                show_item_2 = any(any(p.lower().endswith(ext) for ext in item_2_exts) for p in paths if not os.path.isdir(p))

        if show_item_2:
            item_2 = Caja.MenuItem(
                name="MediaMeshMenu::Action2",
                label="Convert to MKV",
                tip="Convert to MKV",
                icon="video-x-generic",
            )
            item_2.connect("activate", _on_action_2, files)
            submenu.append_item(item_2)
            items_added += 1
        item_3_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts')
        item_3_allow_all = False
        show_item_3 = False

        if has_dir and allow_dirs:
            show_item_3 = True
        elif has_file:
            if item_3_allow_all:
                show_item_3 = True
            else:
                show_item_3 = any(any(p.lower().endswith(ext) for ext in item_3_exts) for p in paths if not os.path.isdir(p))

        if show_item_3:
            item_3 = Caja.MenuItem(
                name="MediaMeshMenu::Action3",
                label="Convert to WEBM",
                tip="Convert to WEBM",
                icon="video-x-generic",
            )
            item_3.connect("activate", _on_action_3, files)
            submenu.append_item(item_3)
            items_added += 1
        item_4_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts')
        item_4_allow_all = False
        show_item_4 = False

        if has_dir and allow_dirs:
            show_item_4 = True
        elif has_file:
            if item_4_allow_all:
                show_item_4 = True
            else:
                show_item_4 = any(any(p.lower().endswith(ext) for ext in item_4_exts) for p in paths if not os.path.isdir(p))

        if show_item_4:
            item_4 = Caja.MenuItem(
                name="MediaMeshMenu::Action4",
                label="Convert to AV1",
                tip="Convert to AV1",
                icon="video-x-generic",
            )
            item_4.connect("activate", _on_action_4, files)
            submenu.append_item(item_4)
            items_added += 1
        item_5_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts')
        item_5_allow_all = False
        show_item_5 = False

        if has_dir and allow_dirs:
            show_item_5 = True
        elif has_file:
            if item_5_allow_all:
                show_item_5 = True
            else:
                show_item_5 = any(any(p.lower().endswith(ext) for ext in item_5_exts) for p in paths if not os.path.isdir(p))

        if show_item_5:
            item_5 = Caja.MenuItem(
                name="MediaMeshMenu::Action5",
                label="DaVinci Resolve (DNxHD)",
                tip="DaVinci Resolve (DNxHD)",
                icon="video-x-generic",
            )
            item_5.connect("activate", _on_action_5, files)
            submenu.append_item(item_5)
            items_added += 1
        item_6_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts')
        item_6_allow_all = False
        show_item_6 = False

        if has_dir and allow_dirs:
            show_item_6 = True
        elif has_file:
            if item_6_allow_all:
                show_item_6 = True
            else:
                show_item_6 = any(any(p.lower().endswith(ext) for ext in item_6_exts) for p in paths if not os.path.isdir(p))

        if show_item_6:
            item_6 = Caja.MenuItem(
                name="MediaMeshMenu::Action6",
                label="Apple ProRes (HQ)",
                tip="Apple ProRes (HQ)",
                icon="video-x-generic",
            )
            item_6.connect("activate", _on_action_6, files)
            submenu.append_item(item_6)
            items_added += 1
        item_7_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts', '.mp3', '.aac', '.wav', '.flac', '.ogg', '.m4a')
        item_7_allow_all = False
        show_item_7 = False

        if has_dir and allow_dirs:
            show_item_7 = True
        elif has_file:
            if item_7_allow_all:
                show_item_7 = True
            else:
                show_item_7 = any(any(p.lower().endswith(ext) for ext in item_7_exts) for p in paths if not os.path.isdir(p))

        if show_item_7:
            item_7 = Caja.MenuItem(
                name="MediaMeshMenu::Action7",
                label="Extract Audio (MP3)",
                tip="Extract Audio (MP3)",
                icon="audio-x-generic",
            )
            item_7.connect("activate", _on_action_7, files)
            submenu.append_item(item_7)
            items_added += 1
        item_8_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts', '.mp3', '.aac', '.wav', '.flac', '.ogg', '.m4a')
        item_8_allow_all = False
        show_item_8 = False

        if has_dir and allow_dirs:
            show_item_8 = True
        elif has_file:
            if item_8_allow_all:
                show_item_8 = True
            else:
                show_item_8 = any(any(p.lower().endswith(ext) for ext in item_8_exts) for p in paths if not os.path.isdir(p))

        if show_item_8:
            item_8 = Caja.MenuItem(
                name="MediaMeshMenu::Action8",
                label="Extract Audio (AAC)",
                tip="Extract Audio (AAC)",
                icon="audio-x-generic",
            )
            item_8.connect("activate", _on_action_8, files)
            submenu.append_item(item_8)
            items_added += 1
        item_9_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts', '.mp3', '.aac', '.wav', '.flac', '.ogg', '.m4a')
        item_9_allow_all = False
        show_item_9 = False

        if has_dir and allow_dirs:
            show_item_9 = True
        elif has_file:
            if item_9_allow_all:
                show_item_9 = True
            else:
                show_item_9 = any(any(p.lower().endswith(ext) for ext in item_9_exts) for p in paths if not os.path.isdir(p))

        if show_item_9:
            item_9 = Caja.MenuItem(
                name="MediaMeshMenu::Action9",
                label="Extract Audio (WAV)",
                tip="Extract Audio (WAV)",
                icon="audio-x-generic",
            )
            item_9.connect("activate", _on_action_9, files)
            submenu.append_item(item_9)
            items_added += 1
        item_10_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts', '.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.ico')
        item_10_allow_all = False
        show_item_10 = False

        if has_dir and allow_dirs:
            show_item_10 = True
        elif has_file:
            if item_10_allow_all:
                show_item_10 = True
            else:
                show_item_10 = any(any(p.lower().endswith(ext) for ext in item_10_exts) for p in paths if not os.path.isdir(p))

        if show_item_10:
            item_10 = Caja.MenuItem(
                name="MediaMeshMenu::Action10",
                label="Convert to GIF",
                tip="Convert to GIF",
                icon="image-x-generic",
            )
            item_10.connect("activate", _on_action_10, files)
            submenu.append_item(item_10)
            items_added += 1
        item_11_exts = ('.mp4', '.mkv', '.webm', '.mov', '.avi', '.wmv', '.flv', '.ts', '.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.ico')
        item_11_allow_all = False
        show_item_11 = False

        if has_dir and allow_dirs:
            show_item_11 = True
        elif has_file:
            if item_11_allow_all:
                show_item_11 = True
            else:
                show_item_11 = any(any(p.lower().endswith(ext) for ext in item_11_exts) for p in paths if not os.path.isdir(p))

        if show_item_11:
            item_11 = Caja.MenuItem(
                name="MediaMeshMenu::Action11",
                label="Convert to WEBP",
                tip="Convert to WEBP",
                icon="image-x-generic",
            )
            item_11.connect("activate", _on_action_11, files)
            submenu.append_item(item_11)
            items_added += 1
        item_12_exts = ('.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.ico')
        item_12_allow_all = False
        show_item_12 = False

        if has_dir and allow_dirs:
            show_item_12 = True
        elif has_file:
            if item_12_allow_all:
                show_item_12 = True
            else:
                show_item_12 = any(any(p.lower().endswith(ext) for ext in item_12_exts) for p in paths if not os.path.isdir(p))

        if show_item_12:
            item_12 = Caja.MenuItem(
                name="MediaMeshMenu::Action12",
                label="Convert to JPG",
                tip="Convert to JPG",
                icon="image-x-generic",
            )
            item_12.connect("activate", _on_action_12, files)
            submenu.append_item(item_12)
            items_added += 1
        item_13_exts = ('.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.ico')
        item_13_allow_all = False
        show_item_13 = False

        if has_dir and allow_dirs:
            show_item_13 = True
        elif has_file:
            if item_13_allow_all:
                show_item_13 = True
            else:
                show_item_13 = any(any(p.lower().endswith(ext) for ext in item_13_exts) for p in paths if not os.path.isdir(p))

        if show_item_13:
            item_13 = Caja.MenuItem(
                name="MediaMeshMenu::Action13",
                label="Convert to BMP",
                tip="Convert to BMP",
                icon="image-x-generic",
            )
            item_13.connect("activate", _on_action_13, files)
            submenu.append_item(item_13)
            items_added += 1
        item_14_exts = ('.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.ico')
        item_14_allow_all = False
        show_item_14 = False

        if has_dir and allow_dirs:
            show_item_14 = True
        elif has_file:
            if item_14_allow_all:
                show_item_14 = True
            else:
                show_item_14 = any(any(p.lower().endswith(ext) for ext in item_14_exts) for p in paths if not os.path.isdir(p))

        if show_item_14:
            item_14 = Caja.MenuItem(
                name="MediaMeshMenu::Action14",
                label="Convert to ICO",
                tip="Convert to ICO",
                icon="image-x-generic",
            )
            item_14.connect("activate", _on_action_14, files)
            submenu.append_item(item_14)
            items_added += 1
        if items_added == 0:
            return []

        return [top_item]
